server:
  port: 8081

spring:

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tradearena_auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: krithikaaie21@gmail.com
    password: ztftppfuxvqiuvon
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: TradeArena@SecretKey#2025$JwtAuth!HS256Ready
    expiration : 3600000

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka