server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**


app:
  jwt:
    secret: TradeArena@SecretKey#2025$JwtAuth!HS256Ready


eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true